# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Michael D Peters
tagline:          'A blog'
description:      'Random musings on programming, glass fusing and other nonsense.'
url:              http://blog.michaeldpeters.com
baseurl:          /

author:
  name:           'Michael Peters'
  url:            https://michaeldpeters.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bluehawk/blog
